# Generated by Django 6.1.1 on 2026-09-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveBigIntegerField(db_index=True, unique=True)),
                ('prev_hash', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=64)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
    ]
