# Generated by Django 6.1.1 on 2026-09-21 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveBigIntegerField(db_index=True, unique=True)),
                ('prev_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='ChainHead',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('last_seq', models.PositiveBigIntegerField()),
                ('last_hash', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MerkleAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_start', models.PositiveBigIntegerField()),
                ('seq_end', models.PositiveBigIntegerField()),
                ('merkle_root', models.CharField(max_length=64)),
                ('prev_root', models.CharField(blank=True, max_length=64, null=True)),
                ('external_ref', models.CharField(blank=True, max_length=255)),
                ('anchored_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AuditEntry',
        ),
        migrations.AddConstraint(
            model_name='chainhead',
            constraint=models.CheckConstraint(condition=models.Q(('id', 1)), name='chainhead_singleton'),
        ),
    ]
